plugin:
    has_options: false
    icon: icap_badge_icon.png

    widgets:
      - name: badge_usage
        is_configurable: true
        is_exportable: false

    tools:
      - name: badges
        class: trophy
        is_displayable_in_workspace: true
        is_displayable_in_desktop: false
      - name: my_badges
        class: trophy
        is_displayable_in_workspace: true
        is_displayable_in_desktop: false

    admin_tools:
      - name: badges_management
        class: trophy