idci_exporter:
    entities:
        badge:
            class: 'Claroline\CoreBundle\Entity\Badge\Badge'
            formats:
                jsonp:
                    transformer:
                        service: "icap.transformer.badge"
                        options:
                            template_name_format: 'export.json.twig'
